import type { Metadata } from 'next';
import { Anek_Latin } from 'next/font/google';

const anek_latin = Anek_Latin({ subsets: ['latin'] });

//styles
import '../../public/assets/css/styles.css';
import '../../public/assets/css/vendors/tailwind.css';
import 'swiper/css';
import 'swiper/css/pagination';

import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';


export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={anek_latin.className}>
        <Header />

        <main className='main'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
